# Generated by Django 4.1.3 on 2022-11-07 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="message",
            field=models.TextField(blank=True, null=True),
        ),
    ]
